const API_BASE_URL = 'http://localhost:5000'
const NONOSECONDS_PY = 1;
const MICROSECONDS_PY = 1000 * NONOSECONDS_PY
const MILLISECONDS_PY = 1000 * MICROSECONDS_PY

export {API_BASE_URL, MILLISECONDS_PY}